name: Abundant-Skyblock
version: '${project.version}'
main: net.abundantmc.abundantskyblock.AbundantSkyblock
api-version: '1.20'
commands:
  gamemode:
    description: Gamemode Command
    usage: /gamemode <gamemode>
    permission: abundant.command.gamemode
    permission-message: You do not have permission for this!
  warpgui:
    description: Opens the Warp GUI
    usage: /warpgui
    permission: abundant.command.warpgui
    permission-message: You do not have permission for this!